import type { Metadata, Viewport } from "next";
import { Geist_Mono } from "next/font/google";
import MainLayout from "@/components/layout";
import AppProvider from "@/provider/AppProvider";
import CommonToast from "@/components/common-toast";
import SolanaProvider from "@/provider/SolanaProvider";
import GoogleAnalytics from "@/components/GoogleAnalytics";
import "./globals.css";

const geist = Geist_Mono({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Lander",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geist.variable}  antialiased`}>
        <GoogleAnalytics />
        <SolanaProvider>
          <MainLayout>{children}</MainLayout>
          <AppProvider />
          <CommonToast />
        </SolanaProvider>
      </body>
    </html>
  );
}
